name: flutter_oss_manager
description: "A Flutter package and CLI for scanning, summarizing, and
  generating open-source license information for your project's dependencies."
keywords:
  - license
  - oss
  - dependencies
  - automation
  - cli
  - tool
  - generator
version: 1.0.2
homepage: https://github.com/kihyun1998/flutter_oss_manager
repository: https://github.com/kihyun1998/flutter_oss_manager

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  args: ^2.4.2
  flutter:
    sdk: flutter
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

executables:
  flutter_oss_manager:
